[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dmrv_ledger = "11111111111111111111111111111111"   # placeholder, see lib.rs

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
